version: "3"
services:
  # Redis
  redis-server:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"

  # mysql user server
  mysql-user:
    build:
      dockerfile: Dockerfile
      context: ./mysql-user
    restart: unless-stopped
    container_name: mysql-user
    ports:
      - "40051:3306"
    volumes:
      - ./mysql-user/mysql_data:/var/lib/mysql
      - ./mysql-user/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: fira_user_password
      MYSQL_DATABASE: fira_user

  # mysql model_version server
  mysql-model_version:
    build:
      dockerfile: Dockerfile
      context: ./mysql-model_version
    restart: unless-stopped
    container_name: mysql-model_version
    ports:
      - "40053:3306"
    volumes:
      - ./mysql-model_version/mysql_data:/var/lib/mysql
      - ./mysql-model_version/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: fira_model_version_password
      MYSQL_DATABASE: fira_model_version

  # user server
  api-user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: fira/api-user
    ports:
      - "50051:50051"
    restart: on-failure
    depends_on:
      - mysql-user
      - redis-server

  # model_version server
  api-model_version:
    build:
      context: ./model_version
      dockerfile: Dockerfile
    image: fira/api-model_version
    ports:
      - "50053:50053"
    restart: always
    depends_on:
      - mysql-model_version
      - api-user


