// source: user_fix_image.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var empty_pb = require('./empty_pb.js');
goog.object.extend(proto, empty_pb);
goog.exportSymbol('proto.UserFixedImageInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UserFixedImageInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.UserFixedImageInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.UserFixedImageInfo.displayName = 'proto.UserFixedImageInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UserFixedImageInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.UserFixedImageInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UserFixedImageInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserFixedImageInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    imageContent: msg.getImageContent_asB64(),
    fileName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    exifDegree: jspb.Message.getFieldWithDefault(msg, 3, 0),
    modelDegree: jspb.Message.getFieldWithDefault(msg, 4, 0),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    userFixDegree: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UserFixedImageInfo}
 */
proto.UserFixedImageInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.UserFixedImageInfo;
  return proto.UserFixedImageInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UserFixedImageInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UserFixedImageInfo}
 */
proto.UserFixedImageInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setImageContent(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFileName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setExifDegree(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setModelDegree(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setConfidence(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUserFixDegree(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UserFixedImageInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.UserFixedImageInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UserFixedImageInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserFixedImageInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getImageContent_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getFileName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExifDegree();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getModelDegree();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getUserFixDegree();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional bytes image_content = 1;
 * @return {string}
 */
proto.UserFixedImageInfo.prototype.getImageContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes image_content = 1;
 * This is a type-conversion wrapper around `getImageContent()`
 * @return {string}
 */
proto.UserFixedImageInfo.prototype.getImageContent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImageContent()));
};


/**
 * optional bytes image_content = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImageContent()`
 * @return {!Uint8Array}
 */
proto.UserFixedImageInfo.prototype.getImageContent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImageContent()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.UserFixedImageInfo} returns this
 */
proto.UserFixedImageInfo.prototype.setImageContent = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional string file_name = 2;
 * @return {string}
 */
proto.UserFixedImageInfo.prototype.getFileName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.UserFixedImageInfo} returns this
 */
proto.UserFixedImageInfo.prototype.setFileName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 exif_degree = 3;
 * @return {number}
 */
proto.UserFixedImageInfo.prototype.getExifDegree = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.UserFixedImageInfo} returns this
 */
proto.UserFixedImageInfo.prototype.setExifDegree = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 model_degree = 4;
 * @return {number}
 */
proto.UserFixedImageInfo.prototype.getModelDegree = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.UserFixedImageInfo} returns this
 */
proto.UserFixedImageInfo.prototype.setModelDegree = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional float confidence = 5;
 * @return {number}
 */
proto.UserFixedImageInfo.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.UserFixedImageInfo} returns this
 */
proto.UserFixedImageInfo.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional int32 user_fix_degree = 6;
 * @return {number}
 */
proto.UserFixedImageInfo.prototype.getUserFixDegree = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.UserFixedImageInfo} returns this
 */
proto.UserFixedImageInfo.prototype.setUserFixDegree = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


goog.object.extend(exports, proto);
